<ul class="nav nav-principal align-items-center justify-content-between border-bottom sticky-top d-flex">
    <li class="">
        <a href="" class="nav-link"><span> Para você</span></a>
    </li>
    <li class="nav-item ativo">
        <a href="" class="nav-link"><span class="">Assuntos do momento</span></a>
    </li>
    <li class="nav-item ">
        <a href="" class="nav-link"><span> Notícias</span></a>
    </li>
    <li class="nav-item ">
        <a href="" class="nav-link"><span> Esportes</span></a>
    </li>
    <li class="nav-item ">
        <a href="" class="nav-link"><span> Entreterimento</span></a>
    </li>
</ul></div>