<ul class="navbar-nav d-flex flex-column navegacao">
    <li class="nav-item">
        <a href="" class="nav-link rounded-pill ativo">
            <i class="fa-sharp fa-solid fa-hashtag"></i><span class="d-xl-inline d-none" id="explorar">Explorar</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="" class="nav-link rounded-pill">
            <i class="fa-regular fa-gear"></i><span class="d-xl-inline d-none" id="configuracao" >Configurações</span>
        </a>
    </li>
    
</ul>