<div class="inscrever border rounded-4">
    <h4>Novo no Twitter?</h4>
    <p>Inscreva-se para ter sua própria timeline personalizada!</p>
    <button class="rounded-pill border fw-normal btn-google"><img src="img/google.svg" height="30" alt=""> Inscrever-se no Google</button>
    <button class="rounded-pill border"><i class="fa-brands fa-xl fa-apple me-2"></i>Inscrever-se com Apple</button>
    <button class="rounded-pill border text-truncate"><span class="mx-2 ">Inscrever-se com número de celular</span></button>
    <p id="texto-inscrever">Ao se inscrever, você concorda com os <a class="link-azul" href="">Termos de Serviço </a> e a <a class="link-azul" href="">Política
            de Privacidade</a>, incluindo o Uso de Cookies.</p>
</div>