</div>
    <div href="" class="postagem-conteudo d-flex w-100 align-items-center border-start border-end">
        <i class="fa-solid fa-user icon-postagem"></i>
        <div class="d-flex input-postagem w-100">
        <form action="/tweet" method="post">
            <input type="text" name="tweet" placeholder="What's happening?">
        
        </div>
        
    </div>
    <div class="icons d-flex border-bottom border-start border-end">
        <i class="fa-solid rounded-circle fa-image"></i>
        <i class="fa-solid rounded-circle fa-file-image"></i>
        <i class="fa-solid rounded-circle fa-list-ul"></i>
        <i class="fa-solid rounded-circle fa-face-smile"></i>
        <i class="fa-solid rounded-circle fa-calendar-days"></i>
        <i class="fa-solid rounded-circle fa-location-dot"></i>
        <button class="ms-auto rounded-pill tweet-postagem ">Tweet</button>
        </form>
    </div>
