<div class="col-12 d-flex  align-items-center border-start border-end">
    <div class="home-top d-flex align-items-center">
        <i class="fa-solid fa-arrow-left"></i>
        <div class="user-top d-flex flex-column">
        <h5><?  print_r($this->view->info_user)?></h5>
        <p><?= $this->view->totalTweets['total']?> tweets</p>
        </div>
        <i class="fa-regular fa-star star"></i>
    </div>
</div>