<div class=" aside-buscar">
    <div class="aside-pesquisar rounded-pill">
        <i class="fa-thin fa-solid rounded-end-pill fa-magnifying-glass" id="aside-pesquisar" ></i>
        <input type="text" placeholder="Search Twitter">
    </div>
</div>
<div class=" h-auto rounded-4">
    <div class="aside-timeline d-flex flex-column rounded-4 mt-2">
        <h4>What’s happening</h4>
        
        <a href="" class="link-conteudo">
            <p class="me-auto">Assuntos no momento</p>
            <i class="fa-solid fa-ellipsis icon-conteudo rounded-circle"></i>
            <h5>Quem no bts</h5>
            <p>1345 tweets</p>
        </a><a href="" class="link-conteudo">
            <p class="me-auto">Assuntos no momento</p>
            <i class="fa-solid fa-ellipsis icon-conteudo rounded-circle"></i>
            <h5>Quem no bts</h5>
            <p>1345 tweets</p>
        </a>
        <a href="" class="link-conteudo">
            <p class="me-auto">Assuntos no momento</p>
            <i class="fa-solid fa-ellipsis icon-conteudo rounded-circle"></i>
            <h5>Quem no bts</h5>
            <p>1345 tweets</p>
        </a><a href="" class="link-conteudo">
            <p class="me-auto">Assuntos no momento</p>
            <i class="fa-solid fa-ellipsis icon-conteudo rounded-circle"></i>
            <h5>Quem no bts</h5>
            <p>1345 tweets</p>
        </a>
        <a class="link-conteudo  rounded-bottom-4" href="\quem_seguir">Show More</a>
    </div>
    <div class="aside-timeline d-flex flex-column rounded-4 mt-3">
        <h4>Who to follow</h4>
        
       
        <a href="" class="d-flex align-items-center link-conteudo">
            <div class="user-foto rounded-circle">
                <i class="fa-solid fa-user"></i>
            </div>
            <div class=" d-flex flex-column w-auto user-text text-truncate">
                <h5>Jeca</h5>
                <p>@johnatas_ls</p>
            </div>
            <button class="ms-auto rounded-pill">Follow</button>
        </a>
        <a href="" class="d-flex align-items-center link-conteudo">
            <div class="user-foto rounded-circle">
                <i class="fa-solid fa-user"></i>
            </div>
            <div class=" d-flex flex-column w-auto user-text text-truncate">
                <h5>Jeca</h5>
                <p>@johnatas_ls</p>
            </div>
            <button class="ms-auto rounded-pill">Follow</button>
        </a><a href="" class="d-flex align-items-center link-conteudo">
            <div class="user-foto rounded-circle">
                <i class="fa-solid fa-user"></i>
            </div>
            <div class=" d-flex flex-column w-auto user-text text-truncate">
                <h5>Jeca</h5>
                <p>@johnatas_ls</p>
            </div>
            <button class="ms-auto rounded-pill">Follow</button>
        </a>
        <a class="link-conteudo  rounded-bottom-4" href="\quem_seguir">Show More</a>
    </div>

    
</div>