<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explorar/Twitter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="css/timeline.css">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="css/user.css">
    <link href="FontAwesome/fontawesome-free-6.2.1-web/css/fontawesome.min.css" rel="stylesheet">
    <link href="FontAwesome/fontawesome-free-6.2.1-web/css/brands.min.css" rel="stylesheet">
    <link href="FontAwesome/fontawesome-free-6.2.1-web/css/solid.min.css" rel="stylesheet">
</head>
<body class="">
    <div class="container-fluid h-100">
        <div class="d-flex principal">
            <div class="lado-esquerdo d-flex flex-column justify-content-start ">
                <nav class="navbar d-flex flex-column justify-content-start w-100 align-items-start h-100" id="nav">
                    <div class="col-12 mb-4">
                        <a href="" class="navbar-brand  logo">
                            <img src="img/twitter_logo.png" class="" height="26" alt="">
                        </a>

                    </div>

                    <?= $this->content('lado-esquerdo')?>
                </nav>
            </div>
            <div class="lado-principal h-100">
                <div class="top-principal">
                    <?= $this->content('topo')?>
                    <?= $this->content('cabecalho')?>
                
                <div class="conteudo h-100">
                    <?= $this->content('conteudo')?> 
                </div>
                
            </div>
            <div class="lado-direito h-100">
                <div class="direito-sticky">
                    <?= $this->content('lado-direito')?>
                    <div class="link-direito">
                        <ul class="nav nav-direito">
                            <li><a href="">Termos de Serviço</a></li>
                            <li><a href="">Política de Privacidade</a></li>
                            <li><a href="">Política de Cookies</a></li>
                            <li><a href="">Acessibilidade</a></li>
                            <li><a href="">Informações de anúncios</a></li>
                            <li><a href="">Mais<i class="fa-solid fa-ellipsis ms-1"></i></a></li>
                            <li><a href="">&copy; 2023 Twitter, Inc</i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <?= $this->content('rodape') ?>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="javascript/javascript.js"></script>
</body>

</html>